export default class StatusCampeao {
    private _vida: number;
    private _vidaPorLv: number;
    private _mana: number;
    private _manaPorLv: number;
    private _velocMovimento: number;
    private _armadura: number;
    private _armaduraPorLv: number;
    private _spellblock: number;
    private _spellblockPorLv: number;
    private _alcanceAtck: number;
    private _hpregen: number;
    private _hpregenPorLv: number;
    private _mpregen: number;
    private _mpregenPorLv: number;
    private _crit: number;
    private _critPorLv: number;
    private _attackdamage: number;
    private _attackdamagePorLv: number;
    private _attackspeedPorLv: number;
    private _attackspeed: number;
    constructor(vida: number, vidaPorLv: number, mana: number, manaPorLv: number, velocMovimento: number, armadura: number, armaduraPorLv: number, spellblock: number, spellblockPorLv: number, alcanceAtck: number, hpregen: number, hpregenPorLv: number, mpregen: number, mpregenPorLv: number, crit: number, critPorLv: number, attackdamage: number, attackdamagePorLv: number, attackspeedPorLv: number, attackspeed: number) {
        this._vida = vida;
        this._vidaPorLv = vidaPorLv;
        this._mana = mana;
        this._manaPorLv = manaPorLv;
        this._velocMovimento = velocMovimento;
        this._armadura = armadura;
        this._armaduraPorLv = armaduraPorLv;
        this._spellblock = spellblock;
        this._spellblockPorLv = spellblockPorLv;
        this._alcanceAtck = alcanceAtck;
        this._hpregen = hpregen;
        this._hpregenPorLv = hpregenPorLv;
        this._mpregen = mpregen;
        this._mpregenPorLv = mpregenPorLv;
        this._crit = crit;
        this._critPorLv = critPorLv;
        this._attackdamage = attackdamage;
        this._attackdamagePorLv = attackdamagePorLv;
        this._attackspeedPorLv = attackspeedPorLv;
        this._attackspeed = attackspeed;
    }
    get vida() { return this._vida; };
    get vidaPorLv() { return this._vidaPorLv; };
    get mana() { return this._mana; };
    get manaPorLv() { return this._manaPorLv; };
    get velocMovimento() { return this._velocMovimento; };
    get armadura() { return this._armadura; };
    get armaduraPorLv() { return this._armaduraPorLv; };
    get spellblock() { return this._spellblock; };
    get spellblockPorLv() { return this._spellblockPorLv; };
    get alcanceAtck() { return this._alcanceAtck; };
    get hpregen() { return this._hpregen; };
    get hpregenPorLv() { return this._hpregenPorLv; };
    get mpregen() { return this._mpregen; };
    get mpregenPorLv() { return this._mpregenPorLv; };
    get crit() { return this._crit; };
    get critPorLv() { return this._critPorLv; };
    get attackdamage() { return this._attackdamage; };
    get attackdamagePorLv() { return this._attackdamagePorLv; };
    get attackspeedPorLv() { return this._attackspeedPorLv; };
    get attackspeed() { return this._attackspeed; };
}